### ISSUE TITLE
Quick Connect takes a user to the Connect Pop-up

### ISSUE THREAD

**Issue by MDAR** [velbus/velbuslink#1]
Hi

Just a tiny observation.

Having used the "Connect" button to define a connection to a Velbus network, I thought I'd use the "Quick Connect" button next.

The "Quick Connect" took me to the same "Connection" pop-up.

(Version 9.xxxx all worked find)

Cheers

Stuart

**Comment by dukeofphilberg** [comment]
Hello Stuart

As discussed in an email conversation, this is currently intended behaviour.
I've since added a task in our project management software to improve functionality ;)

Kind regards
