### ISSUE TITLE
Reading of VMB1RYS goes wrong

### ISSUE THREAD

**Issue by matthijsfh** [velbus/velbuslink#3]
When I read the VMB1RYS module from 10.4.1. the actions read from the module (is that the name?) are added to the actions which were in the original project file.

So each time I read this specific module, I end up with more and more actions in the project. Somehow the SW sees the actions read from the module as different once that were in the module. 

So there are 3 actions defined for a specific channel, and after reading, there are 6 actions in my project. After another read there are 9 actions. Things go south very fast from there. 

VelBusLink detects the changes in the rules and keep wanting to re-write the module. I did that by accident and that made the amount of rules explode.

Will add a screenshot soon.

**Comment by matthijsfh** [comment]
My project as I created it. This did NOT require a read from the VMB1RYS, only writes, so I did not detect the issue before.

![project1](https://user-images.githubusercontent.com/54779898/110440896-737fea00-80b9-11eb-8540-48ffeb195814.png)

By accident, I read VMB1RYS (in fact I read all modules). 

![project2](https://user-images.githubusercontent.com/54779898/110440895-737fea00-80b9-11eb-8283-4d7afb55de17.png)

I can confirm that this is the only module which has this issue. Other modules read back correctly.
Took me some time to detect what was going on. After 2nd read, more rules are added. VelBusLink does not recognize that the rules are "the same". 

![project3](https://user-images.githubusercontent.com/54779898/110440894-724ebd00-80b9-11eb-9533-dfff51b08e68.png)




Is the module broken? Or is it a software bug?

Grtz Matthijs

**Comment by matthijsfh** [comment]
Replacement module (brand new) has identical problem. Velbus version 10.4.3

Each read from the module doubles the rules.

**Comment by matthijsfh** [comment]
Additional testing shows that first version which supports this module is 10.2.4. This version also does NOT work correctly on a brand new module.

Checked the logging, no other modules are send messages.

**Comment by dukeofphilberg** [comment]
Sorry for not catching the issue here! As you mentioned [on the forum](https://forum.velbus.eu/t/rules-double-after-each-vmb1rys-read-action/16502/5) it is fixed with 10.4.4.0.
