### ISSUE TITLE
VelbusLink installer V10.6.2 gives erros

### ISSUE THREAD

**Issue by JornHermans** [velbus/velbuslink#4]
The installer gives an error when installing VelbusLink 10.6.2, it states that 3or4 documents already exists, to get it installed i ignored it and didn't replace the files (it are the .html files).

**Comment by dukeofphilberg** [comment]
Hello @JornHermans, thanks for the report. Unfortunately we are unable to reproduce the issue. If you would install the same version, does this error occur again?

**Comment by JornHermans** [comment]
![1](https://user-images.githubusercontent.com/34610908/132748934-59914d8a-5921-4b87-9482-a19385a7a982.jpg)
![2](https://user-images.githubusercontent.com/34610908/132748936-a202dbc4-74ec-45b5-b2d4-ef3c092b07a9.jpg)
![3](https://user-images.githubusercontent.com/34610908/132748938-96b2a639-70b7-4fbd-bc08-37e5df21b11c.jpg)


yes it does!

**Comment by dukeofphilberg** [comment]
Hello @JornHermans, we've resolved this issue in VelbusLink version 10.6.3. 

If you experience any more problems let us know!
